#!/usr/bin/env zsh
# set $0 (ref: zdharma.org/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html#zero-handling)
0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
0="${${(M)0:#/*}:-$PWD/$0}"

# load library functions
fpath+=("${0%/*}/lib")
autoload -z ls-color::{init,from-mode,from-name}

# init (sets modecolors and namecolors)
ls-color::init

# color each file in the argument list
local file reply
for file; do
	ls-color::from-name $file 3

	# point to symlink resolution if it exists
	print '\e['$reply[1]'m'$file'\e[0m'${reply[3]:+' → \e['$reply[3]'m'$reply[4]'\e[0m'}
done
