#!/usr/bin/env zsh
emulate -L zsh
# Use LSCOLORS on BSD
local LS_COLORS=${LS_COLORS=$LSCOLORS}

# read in LS_COLORS
typeset -gA namecolors=(${(@s:=:)${(@s.:.)LS_COLORS}:#[[:alpha:]][[:alpha:]]=*})
typeset -gA ftcolors=(${(@Ms:=:)${(@s.:.)LS_COLORS}:#[[:alpha:]][[:alpha:]]=*})

