#!/usr/bin/env zsh
# Usage:
# $1: filename
# $2: The value of struct stat st_mode
#     If empty, modecolors lookup will be skipped
#
# Sets REPLY to the console code

emulate -L zsh
setopt cbases octalzeroes extendedglob

[[ -z $2 ]] && return 1

local -i reg=0
local -a codes


local -i st_mode=$(($2))
# See man 7 inode for more info
# file type
case $(( st_mode & 0170000 )) in
	$(( 0140000 )) ) codes=( $modecolors[so] ) ;;
	$(( 0120000 )) ) # symlink, special handling
		if [[ -e $1 ]]
		then REPLY=$modecolors[ln]
		else REPLY=$modecolors[or]
		fi
		return
	;;
	$(( 0100000 )) ) codes=( ); reg=1 ;; # regular file
	$(( 0060000 )) ) codes=( $modecolors[bd] ) ;;
	$(( 0040000 )) ) codes=( $modecolors[di] ) ;;
	$(( 0020000 )) ) codes=( $modecolors[cd] ) ;;
	$(( 0010000 )) ) codes=( $modecolors[pi] ) ;;
esac

# setuid/setgid/sticky/other-writable
(( st_mode & 04000 )) && codes+=( $modecolors[su] )
(( st_mode & 02000 )) && codes+=( $modecolors[sg] )
(( ! reg )) && case $(( st_mode & 01002 )) in
	# sticky
	$(( 01000 )) ) codes+=( $modecolors[st] ) ;;
	# other-writable
	$(( 00002 )) ) codes+=( $modecolors[ow] ) ;;
	# other-writable and sticky
	$(( 01002 )) ) codes+=( $modecolors[tw] ) ;;
esac

# executable
if (( ! $#codes )); then
	(( st_mode &  0111 )) && codes+=( $modecolors[ex] )
fi

# return nonzero if no matching code
[[ ${REPLY::=${(j:;:)codes}} ]]
